version: '2'
services:

  customer-service:
    image: java:alpine
    ports:
      - "8081:8081"
    volumes:
      - $DIR/../customer-service/target/customer-service-fat.jar:/var/app.jar:z
      - $DIR/../customer-service/src/main/conf/config.json:/etc/config.json:ro
    command: java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory -jar /var/app.jar -conf /etc/config.json

  vehicle-service:
    image: java:alpine
    ports:
      - "8082:8082"
    volumes:
      - $DIR/../vehicle-service/target/vehicle-service-fat.jar:/var/app.jar:z
      - $DIR/../vehicle-service/src/main/conf/config.json:/etc/config.json
    command: java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory -jar /var/app.jar -conf /etc/config.json

  rental-service:
    image: java:alpine
    ports:
      - "8083:8083"
    volumes:
      - $DIR/../rental-service/target/rental-service-fat.jar:/var/app.jar:z
      - $DIR/../rental-service/src/main/conf/config.json:/etc/config.json
    command: java -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory -jar /var/app.jar -conf /etc/config.json

  graphql-service:
    image: java:alpine
    ports:
      - "8080:8080"
    links:
      - customer-service
      - vehicle-service
      - rental-service
    depends_on:
      - customer-service
      - vehicle-service
      - rental-service
    volumes:
      - $DIR/../graphql-service/target/graphql-service-fat.jar:/var/app.jar:z
      - $DIR/../graphql-service/src/main/conf/docker.json:/etc/config.json
    command: java -Dvertx.disableDnsResolver=true -Dvertx.logger-delegate-factory-class-name=io.vertx.core.logging.SLF4JLogDelegateFactory -jar /var/app.jar -conf /etc/config.json
